# -*- coding: utf-8 -*-
"""클러스터링 EDA & TCN_공유본.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LercCAbVlldqyRtqIe1jUyaYy6Bxc-TD

## 클러스터링 EDA
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns
from typing import List

# 경고 메시지 무시
import warnings
warnings.filterwarnings('ignore')

# 헬퍼 함수 (사용자 코드에서 가져옴)
def get_menu_category(menu_name: str) -> str:
    menu_lower = menu_name.lower()
    if any(word in menu_lower for word in ['막걸리', '소주', '맥주', '와인', '참이슬', '처음처럼', '카스', '하이네켄', '버드와이저', '스텔라']):
        return 'alcohol'
    elif any(word in menu_lower for word in ['찌개', '탕', '국밥', '라면', '해장국', '갈비탕']):
        return 'hot_food'
    elif any(word in menu_lower for word in ['삼겹', '갈비', '목살', 'bbq', '구이', '불고기']):
        return 'bbq'
    elif any(word in menu_lower for word in ['아이스크림', '식혜', '콜라', '스프라이트', '에이드']):
        return 'dessert_drink'
    elif any(word in menu_lower for word in ['아메리카노', '라떼', '커피']):
        return 'coffee'
    elif any(word in menu_lower for word in ['냉면', '파스타', '스파게티', '면', '우동']):
        return 'noodles'
    elif any(word in menu_lower for word in ['비빔밥', '볶음밥', '공깃밥', '정식']):
        return 'rice'
    else:
        return 'others'

def run_menu_visualization_eda(train_csv_path: str):
    # 1. 데이터 로드 및 클러스터링 피처 생성
    print("1. 데이터 로드 및 피처 생성...")
    df = pd.read_csv(train_csv_path)
    df['영업일자'] = pd.to_datetime(df['영업일자'])

    if '영업장명_메뉴명' not in df.columns:
        df['영업장명_메뉴명'] = df['영업장명'] + '_' + df['메뉴명']

    menu_stats = df.groupby('영업장명_메뉴명')['매출수량'].agg(['mean', 'std']).fillna(0).reset_index()
    menu_stats.rename(columns={'mean': 'avg_sales', 'std': 'std_sales'}, inplace=True)

    df['요일'] = df['영업일자'].dt.dayofweek
    menu_weekday_sales = df.groupby(['영업장명_메뉴명', '요일'])['매출수량'].mean().unstack().fillna(0).reset_index()
    menu_weekday_sales.columns = ['영업장명_메뉴명'] + [f'weekday_sales_{i}' for i in range(7)]

    df['월'] = df['영업일자'].dt.month
    menu_month_sales = df.groupby(['영업장명_메뉴명', '월'])['매출수량'].mean().unstack().fillna(0).reset_index()
    menu_month_sales.columns = ['영업장명_메뉴명'] + [f'month_sales_{i}' for i in range(1, 13)]

    menu_stats['메뉴명'] = menu_stats['영업장명_메뉴명'].apply(lambda x: x.split('_', 1)[1])
    menu_stats['menu_category'] = menu_stats['메뉴명'].apply(get_menu_category)

    clustering_df = menu_stats.merge(menu_weekday_sales, on='영업장명_메뉴명')
    clustering_df = clustering_df.merge(menu_month_sales, on='영업장명_메뉴명')

    features_for_clustering = clustering_df.drop(columns=['영업장명_메뉴명', '메뉴명', 'menu_category'])
    scaler = MinMaxScaler()
    scaled_features = scaler.fit_transform(features_for_clustering)

    # 2. PCA 및 클러스터링 적용
    print("2. PCA 및 클러스터링 적용...")
    pca = PCA(n_components=2, random_state=42)
    pca_result = pca.fit_transform(scaled_features)
    clustering_df['pca1'] = pca_result[:, 0]
    clustering_df['pca2'] = pca_result[:, 1]

    # 📌 새로 추가된 코드: PCA의 분산 설명량 출력
    print(f"\n--- PCA 분산 설명량 ---")
    print(f"✅ X축 (주성분 1)의 분산 설명량: {pca.explained_variance_ratio_[0]*100:.2f}%")
    print(f"✅ Y축 (주성분 2)의 분산 설명량: {pca.explained_variance_ratio_[1]*100:.2f}%")
    print(f"✅ 두 주성분의 누적 분산 설명량: {pca.explained_variance_ratio_.sum()*100:.2f}%\n")

    # 📌 새로 추가된 코드: 주성분별 피처 가중치 출력
    pca_loadings = pd.DataFrame(pca.components_.T,
                                columns=['PC1', 'PC2'],
                                index=features_for_clustering.columns)
    print("--- 주성분별 피처 가중치 (상위 5개) ---")
    print("\n✅ X축 (주성분 1) 가중치:")
    print(pca_loadings['PC1'].abs().sort_values(ascending=False).head())
    print("\n✅ Y축 (주성분 2) 가중치:")
    print(pca_loadings['PC2'].abs().sort_values(ascending=False).head())

    kmeans = KMeans(n_clusters=8, random_state=42)
    clustering_df['cluster_id'] = kmeans.fit_predict(scaled_features)

    # 3. 시각화
    print("3. 시각화...")
    plt.figure(figsize=(15, 12))

    sns.scatterplot(x='pca1', y='pca2', hue='cluster_id', data=clustering_df, palette='tab10', legend='full', s=100, alpha=0.7)

    for i, row in clustering_df.sample(5).iterrows():
        plt.text(row['pca1'] + 0.02, row['pca2'] + 0.02, row['영업장명_메뉴명'], fontsize=9)

    plt.title('Menu Items Visualization by Sales Tendency (PCA)')
    plt.xlabel(f'Principal Component 1 ({pca.explained_variance_ratio_[0]*100:.1f}%)')
    plt.ylabel(f'Principal Component 2 ({pca.explained_variance_ratio_[1]*100:.1f}%)')
    plt.grid(True)
    plt.show()

    print("✅ 시각화 완료! 유사한 판매 패턴을 가진 메뉴들은 가까이에 위치합니다.")

    print("--- 모든 클러스터에 속한 메뉴들 (샘플) ---")
    for cluster_id in sorted(clustering_df['cluster_id'].unique()):
        cluster_menus = clustering_df[clustering_df['cluster_id'] == cluster_id]
        print(f"\n[클러스터 {cluster_id}] (총 {len(cluster_menus)}개 메뉴)")
        print(cluster_menus[['영업장명_메뉴명', 'menu_category']].head(5))

    target_cluster_id = 0
    print(f"\n--- 클러스터 {target_cluster_id}의 전체 메뉴 ---")
    full_list = clustering_df[clustering_df['cluster_id'] == target_cluster_id][['영업장명_메뉴명', 'menu_category']]
    print(full_list)

# 메인 실행
if __name__ == '__main__':
    run_menu_visualization_eda('./data/train/train.csv')

"""##TCN"""

# -*- coding: utf-8 -*-
"""
Enhanced TCN Model - 전체 코드
- 목표: N-HiTS 구조에 TCN 모델을 적용하여 성능 개선
- 핵심: TCN 모델 + Enhanced Features + Ultra HurdleLoss + 최적화
"""
import os
import math
import random
import warnings
from dataclasses import dataclass
from typing import List, Dict, Tuple, Optional

import numpy as np
import pandas as pd
import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as F
import glob
from torch.optim.swa_utils import AveragedModel

warnings.filterwarnings('ignore')

# =====================
# Enhanced N-HiTS Config for Colab A100 (TCN에 맞게 재사용)
# =====================
@dataclass
class EnhancedNHiTSConfig:
    # 경로
    train_csv: str = "./data/train/train.csv"
    test_glob: str = "./data/test/*.csv"
    submission_template_csv: str = "./data/sample_submission.csv"
    out_submission_csv: str = "./data/enhanced_tcn_submission.csv" # 경로 주의하세여

    # 컬럼명
    date_col: str = "영업일자"
    item_col: str = "영업장명_메뉴명"
    target_col: str = "매출수량"

    # 윈도우
    in_len: int = 28
    out_len: int = 7

    # 학습 설정
    train_end_date: str = "2024-06-15"
    seed: int = 42
    device: str = "cuda" if torch.cuda.is_available() else "cpu"
    log1p: bool = True

    # A100 최적화 하이퍼파라미터
    EPOCHS_FULL: int = 150
    BATCH_FULL: int = 1024
    BASE_LR_FULL: float = 1e-3
    MAX_LR_FULL: float = 2.5e-3
    WD_FULL: float = 3e-4

    # 튜닝 최적화 (더 정교한 탐색)
    USE_OPTUNA: bool = True
    N_TRIALS: int = 50
    EPOCHS_TUNE: int = 50
    BATCH_TUNE: int = 768

    # CV 설정
    cv_fold_end_dates: Tuple[str, str, str] = ("2024-06-14", "2024-06-07", "2024-05-31")

    # A100 최적화 DataLoader
    num_workers: int = 12
    pin_memory: bool = True
    persistent_workers: bool = True

    # N-HiTS 특화 파라미터 -> TCN 모델에 맞게 조정 가능
    hidden: int = 512
    n_blocks: int = 3
    n_layers: int = 2
    pooling_mode: str = "MaxPool1d"
    interpolation_mode: str = "linear"
    dropout: float = 0.1

    # Multi-scale 설정 (N-HiTS 핵심)
    stack_types: List[str] = None
    n_freq_downsample: List[int] = None

    # Enhanced Loss (극한 최적화)
    eps_smape: float = 0.01
    zero_weight: float = 0.01
    hurdle_lambda: float = 0.15

    # AMP/EMA
    use_amp: bool = True
    use_compile: bool = False
    ema_decay: float = 0.9998

    # 가중치/공휴일
    store_weights: Dict[str, float] = None
    custom_holidays_list: List[str] = None

DEFAULT_STORE_WEIGHTS = {
    "미라시아": 7.71, "담하": 6.51, "연회장": 3.48, "라그로타": 3.44,
    "느티나무 셀프BBQ": 2.78, "화담숲주막": 1.43, "카페테리아": 1.31,
    "화담숲카페": 1.14, "포레스트릿": 1.00,
}

DEFAULT_CUSTOM_HOLIDAYS = [
    '2023-01-01','2023-01-21','2023-01-22','2023-01-23','2023-01-24','2023-03-01','2023-05-01',
    '2023-05-05','2023-05-27','2023-06-06','2023-08-15','2023-09-28','2023-09-29','2023-09-30',
    '2023-10-02','2023-10-03','2023-10-09','2023-12-25',
    '2024-01-01','2024-02-09','2024-02-10','2024-02-11','2024-02-12','2024-03-01','2024-04-10',
    '2024-05-01','2024-05-05','2024-05-06','2024-05-15','2024-06-06','2024-08-15','2024-09-16',
    '2024-09-17','2024-09-18','2024-10-01','2024-10-03','2024-10-09','2024-12-25',
    '2025-01-01','2025-01-28','2025-01-29','2025-01-30','2025-03-01','2025-03-03','2025-05-01',
    '2025-05-05','2025-05-06','2025-06-06','2025-08-15'
]

def set_seed(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

def sine_cosine_encoding(value: float, max_val: float):
    return math.sin(2 * math.pi * value / max_val), math.cos(2 * math.pi * value / max_val)

def get_menu_category(menu_name: str) -> str:
    menu_lower = menu_name.lower()
    if any(word in menu_lower for word in ['막걸리', '소주', '맥주', '와인', '참이슬', '처음처럼', '카스', '하이네켄', '버드와이저', '스텔라']):
        return 'alcohol'
    elif any(word in menu_lower for word in ['찌개', '탕', '국밥', '라면', '해장국', '갈비탕']):
        return 'hot_food'
    elif any(word in menu_lower for word in ['삼겹', '갈비', '목살', 'bbq', '구이', '불고기']):
        return 'bbq'
    elif any(word in menu_lower for word in ['아이스크림', '식혜', '콜라', '스프라이트', '에이드']):
        return 'dessert_drink'
    elif any(word in menu_lower for word in ['아메리카노', '라떼', '커피']):
        return 'coffee'
    elif any(word in menu_lower for word in ['냉면', '파스타', '스파게티', '면', '우동']):
        return 'noodles'
    elif any(word in menu_lower for word in ['비빔밥', '볶음밥', '공깃밥', '정식']):
        return 'rice'
    else:
        return 'others'

def get_store_type(store_name: str) -> str:
    if store_name == "느티나무 셀프BBQ":
        return 'outdoor'
    elif store_name in ["라그로타", "미라시아"]:
        return 'fine_dining'
    elif store_name == "담하":
        return 'traditional'
    elif store_name == "연회장":
        return 'event'
    elif store_name in ["카페테리아", "포레스트릿", "화담숲카페"]:
        return 'casual'
    else:
        return 'specialty'

# 과거 매출 기반 피처를 제거한 build_enhanced_features 함수 # 기존 기수님 코드 피처임
def build_enhanced_features(df: pd.DataFrame, holidays_set: set) -> pd.DataFrame:
    df_copy = df.copy()

    df_copy["dow"] = df_copy["영업일자"].dt.weekday
    df_copy["month"] = df_copy["영업일자"].dt.month
    df_copy["day"] = df_copy["영업일자"].dt.day
    df_copy["week"] = df_copy["영업일자"].apply(lambda d: int(d.isocalendar().week))
    df_copy["quarter"] = df_copy["영업일자"].dt.quarter

    df_copy["is_friday"] = (df_copy["dow"] == 4).astype(int)
    df_copy["is_saturday"] = (df_copy["dow"] == 5).astype(int)
    df_copy["is_sunday"] = (df_copy["dow"] == 6).astype(int)
    df_copy["is_weekend"] = df_copy["dow"].isin([5,6]).astype(int)

    df_copy["is_holiday"] = df_copy["영업일자"].isin(holidays_set).astype(int)
    df_copy["is_off"] = ((df_copy["is_weekend"]==1) | (df_copy["is_holiday"]==1)).astype(int)

    df_copy["tomorrow"] = df_copy["영업일자"] + pd.Timedelta(days=1)
    df_copy["yesterday"] = df_copy["영업일자"] - pd.Timedelta(days=1)
    df_copy["is_before_holiday"] = df_copy["tomorrow"].isin(holidays_set).astype(int)
    df_copy["is_after_holiday"] = df_copy["yesterday"].isin(holidays_set).astype(int)

    df_copy["is_month_start"] = (df_copy["day"] <= 3).astype(int)
    df_copy["is_month_end"] = (df_copy["day"] >= 28).astype(int)

    df_copy["is_spring"] = df_copy["month"].isin([4,5,6]).astype(int)
    df_copy["is_summer"] = df_copy["month"].isin([7,8]).astype(int)
    df_copy["is_autumn"] = df_copy["month"].isin([9,10,11]).astype(int)
    df_copy["is_winter"] = df_copy["month"].isin([12,1,2,3]).astype(int)

    df_copy["is_summer_vacation"] = df_copy["month"].isin([7,8]).astype(int)
    df_copy["is_winter_vacation"] = df_copy["month"].isin([12,1,2]).astype(int)

    df_copy[["month_sin", "month_cos"]] = df_copy["month"].apply(lambda m: pd.Series(sine_cosine_encoding(m, 12)))
    df_copy[["dow_sin", "dow_cos"]] = df_copy["dow"].apply(lambda d: pd.Series(sine_cosine_encoding(d, 7)))
    df_copy[["doy_sin", "doy_cos"]] = df_copy["영업일자"].apply(lambda d: pd.Series(sine_cosine_encoding(d.dayofyear, 365)))
    df_copy[["week_sin", "week_cos"]] = df_copy["week"].apply(lambda w: pd.Series(sine_cosine_encoding(w, 52)))
    df_copy[["quarter_sin", "quarter_cos"]] = df_copy["quarter"].apply(lambda q: pd.Series(sine_cosine_encoding(q, 4)))

    return df_copy.drop(columns=["tomorrow", "yesterday"])

def parse_store_name(item_full: str) -> str:
    return item_full.split("_")[0]

def parse_menu_name(item_full: str) -> str:
    return item_full.split("_", 1)[1] if "_" in item_full else item_full

# ==============================================================================
# 2. Enhanced TCN 모델
# ==============================================================================
class TCNBlock(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size, dilation_factor, dropout_rate):
        super(TCNBlock, self).__init__()
        padding = (kernel_size - 1) * dilation_factor
        self.conv1 = nn.Conv1d(in_channels, out_channels, kernel_size, padding=padding, dilation=dilation_factor)
        self.norm1 = nn.InstanceNorm1d(out_channels)
        self.relu1 = nn.ReLU()
        self.dropout1 = nn.Dropout(dropout_rate)
        self.conv2 = nn.Conv1d(out_channels, out_channels, kernel_size, padding=padding, dilation=dilation_factor)
        self.norm2 = nn.InstanceNorm1d(out_channels)
        self.relu2 = nn.ReLU()
        self.dropout2 = nn.Dropout(dropout_rate)

    def forward(self, x):
        res = x
        out = self.conv1(x)
        out = self.norm1(out[:, :, :-self.conv1.padding[0]])
        out = self.relu1(out)
        out = self.dropout1(out)
        out = self.conv2(out)
        out = self.norm2(out[:, :, :-self.conv2.padding[0]])
        out = self.relu2(out)
        out = self.dropout2(out)
        return out + res

class EnhancedTCNModel(nn.Module):
    def __init__(self, in_len, out_len, cal_dim, n_stores, n_categories, n_types, cfg):
        super().__init__()
        self.in_len = in_len
        self.out_len = out_len

        self.store_emb = nn.Embedding(n_stores, 16)
        self.cat_emb = nn.Embedding(n_categories, 16)
        self.type_emb = nn.Embedding(n_types, 16)

        # NOTE: 과거 매출 기반 피처가 제거되었으므로 cal_dim이 더 작아집니다.
        # 이 코드에서는 cal_dim을 그대로 사용하지만, 실제 피처 수에 맞게 조정될 것입니다.
        input_dim = 1 + 16 + 16 + 16 + cal_dim

        self.tcn_block1 = TCNBlock(input_dim, input_dim, kernel_size=3, dilation_factor=1, dropout_rate=0.1)
        self.tcn_block2 = TCNBlock(input_dim, input_dim, kernel_size=3, dilation_factor=2, dropout_rate=0.1)
        self.tcn_block3 = TCNBlock(input_dim, input_dim, kernel_size=3, dilation_factor=4, dropout_rate=0.1)

        self.fc = nn.Sequential(
            nn.Linear(input_dim * in_len, 256),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(256, out_len * 2)
        )

    def forward(self, x, past_cal, fut_cal, store_idx, cat_idx, type_idx):
        store_emb = self.store_emb(store_idx)
        cat_emb = self.cat_emb(cat_idx)
        type_emb = self.type_emb(type_idx)

        # NOTE: 과거 매출 피처가 없으므로 cal_all은 필요하지 않습니다.
        # past_cal과 fut_cal을 그대로 사용합니다.

        x = x.unsqueeze(-1)
        x_in = torch.cat([
            x,
            store_emb.unsqueeze(1).repeat(1, self.in_len, 1),
            cat_emb.unsqueeze(1).repeat(1, self.in_len, 1),
            type_emb.unsqueeze(1).repeat(1, self.in_len, 1),
            past_cal
        ], dim=-1)

        x_in = x_in.transpose(1, 2)
        out = self.tcn_block1(x_in)
        out = self.tcn_block2(out)
        out = self.tcn_block3(out)
        out = out.transpose(1, 2)

        out = out.reshape(out.shape[0], -1)
        out = self.fc(out)

        v_pred, p_logits = out.chunk(2, dim=-1)

        return v_pred, p_logits

# ==============================================================================
# Enhanced N-HiTS Dataset
# =====================
class EnhancedNHiTSDataset(Dataset):
    def __init__(self, cfg: EnhancedNHiTSConfig, df: pd.DataFrame):
        self.cfg = cfg
        self.df = df.copy()
        self.df[cfg.date_col] = pd.to_datetime(self.df[cfg.date_col])
        self.df[cfg.target_col] = self.df[cfg.target_col].clip(lower=0)

        holidays_set = set(pd.to_datetime(cfg.custom_holidays_list))
        self.df = build_enhanced_features(self.df, holidays_set)

        pivot = self.df.pivot(index=cfg.date_col, columns=cfg.item_col, values=cfg.target_col).sort_index()
        self.items = list(pivot.columns)
        self.dates = list(pivot.index)
        self.values = pivot.fillna(0.0).values.astype(np.float32)

        cal_feats_df = self.df.drop(columns=[cfg.date_col, cfg.item_col, cfg.target_col])
        self.cal_feats = cal_feats_df.values.astype(np.float32)
        self.cal_feat_names = list(cal_feats_df.columns)

        stores = [parse_store_name(it) for it in self.items]
        menus = [parse_menu_name(it) for it in self.items]

        self.store2idx = {s: i for i, s in enumerate(sorted(set(stores)))}
        self.item_store_idx = np.array([self.store2idx[s] for s in stores], dtype=np.int64)
        self.n_stores = len(self.store2idx)

        menu_categories = [get_menu_category(m) for m in menus]
        self.cat2idx = {c: i for i, c in enumerate(sorted(set(menu_categories)))}
        self.item_cat_idx = np.array([self.cat2idx[c] for c in menu_categories], dtype=np.int64)
        self.n_categories = len(self.cat2idx)

        store_types = [get_store_type(s) for s in stores]
        self.type2idx = {t: i for i, t in enumerate(sorted(set(store_types)))}
        self.item_type_idx = np.array([self.type2idx[t] for t in store_types], dtype=np.int64)
        self.n_types = len(self.type2idx)

        sw = cfg.store_weights
        self.sample_weights = np.array([sw.get(parse_store_name(it), 1.0) for it in self.items], dtype=np.float32)

        self.indices: List[Tuple[int,int]] = []
        self.target_end_dates: List[pd.Timestamp] = []
        T = len(self.dates)
        Lx, Ly = cfg.in_len, cfg.out_len
        cutoff = pd.to_datetime(cfg.train_end_date)
        max_start = T - (Lx + Ly)

        for j in range(len(self.items)):
            for t0 in range(0, max_start + 1):
                end_date = self.dates[t0 + Lx + Ly - 1]
                if end_date <= cutoff:
                    self.indices.append((t0, j))
                    self.target_end_dates.append(end_date)
        self.target_end_dates = np.array(self.target_end_dates)

    def __len__(self):
        return len(self.indices)

    def __getitem__(self, idx):
        cfg = self.cfg
        t0, j = self.indices[idx]
        Lx, Ly = cfg.in_len, cfg.out_len

        x = self.values[t0:t0 + Lx, j]
        y = self.values[t0 + Lx:t0 + Lx + Ly, j]

        if cfg.log1p:
            x_in = np.log1p(x)
            y_out = np.log1p(y)
        else:
            x_in, y_out = x.copy(), y.copy()

        # NOTE: 이 부분이 수정되었습니다.
        # 모든 아이템의 캘린더 피처는 동일하므로, j 인덱스를 사용하지 않습니다.
        past_cal = self.cal_feats[t0:t0 + Lx, :]
        fut_cal = self.cal_feats[t0 + Lx:t0 + Lx + Ly, :]

        store_idx = self.item_store_idx[j]
        cat_idx = self.item_cat_idx[j]
        type_idx = self.item_type_idx[j]
        sample_w = self.sample_weights[j]

        zero_mask = (y == 0).astype(np.float32)
        pos_mask = (y > 0).astype(np.float32)

        return {
            "x": torch.from_numpy(x_in).float(),
            "y": torch.from_numpy(y_out).float(),
            "past_cal": torch.from_numpy(past_cal).float(),
            "fut_cal": torch.from_numpy(fut_cal).float(),
            "store_idx": torch.tensor(store_idx, dtype=torch.long),
            "cat_idx": torch.tensor(cat_idx, dtype=torch.long),
            "type_idx": torch.tensor(type_idx, dtype=torch.long),
            "sample_w": torch.tensor(sample_w, dtype=torch.float32),
            "zero_mask": torch.from_numpy(zero_mask).float(),
            "pos_mask": torch.from_numpy(pos_mask).float(),
        }

# ==============================================================================
# 4. Enhanced N-HiTS Trainer (TCN과 동일하게 사용)
# ==============================================================================
class UltraEnhancedHurdleLoss(nn.Module):
    def __init__(self, eps_smape: float, zero_weight: float, hurdle_lambda: float):
        super().__init__()
        self.eps_smape = eps_smape
        self.zero_weight = zero_weight
        self.hurdle_lambda = hurdle_lambda

    def _safe_division(self, a, b):
        return torch.div(a, b + 1e-8)

    def _smape_loss(self, y_pred, y_true):
        denominator = torch.abs(y_true) + torch.abs(y_pred)
        diff = torch.abs(y_true - y_pred)
        return self._safe_division(diff, denominator / 2)

    def _binary_crossentropy(self, p_logits, pos_mask):
        return F.binary_cross_entropy_with_logits(p_logits, pos_mask, reduction='none')

    def forward(self, v_pred, p_logits, y_true, pos_mask, sample_w):
        bce_loss = self._binary_crossentropy(p_logits, pos_mask)
        smape = self._smape_loss(v_pred, y_true)
        smape = torch.where(pos_mask == 1, smape, torch.zeros_like(smape))

        zero_inflated_loss = bce_loss * self.hurdle_lambda
        positive_loss = smape * (1 - self.hurdle_lambda)

        sample_loss = zero_inflated_loss + positive_loss

        total_loss = (sample_loss * sample_w.unsqueeze(1)).mean()

        return total_loss, sample_loss, sample_w.unsqueeze(1)

class EMA:
    def __init__(self, model, decay):
        self.model = model
        self.decay = decay
        self.shadow = {}
        self.backup = {}
        for name, param in model.named_parameters():
            if param.requires_grad:
                self.shadow[name] = param.data.clone()

    def update(self, model):
        for name, param in model.named_parameters():
            if param.requires_grad:
                assert name in self.shadow
                new_average = (1.0 - self.decay) * param.data + self.decay * self.shadow[name]
                self.shadow[name] = new_average.clone()

    def apply_to(self, model):
        self.backup = {}
        for name, param in model.named_parameters():
            if param.requires_grad:
                self.backup[name] = param.data.clone()
                param.data.copy_(self.shadow[name])

    def restore(self, model):
        for name, param in model.named_parameters():
            if param.requires_grad:
                assert name in self.backup
                param.data.copy_(self.backup[name])
        self.backup = {}

class EnhancedNHiTSTrainer:
    def __init__(self, cfg: EnhancedNHiTSConfig, dataset: EnhancedNHiTSDataset, epochs: int,
                 batch_size: int, base_lr: float, max_lr: float, weight_decay: float):
        self.cfg = cfg
        self.dataset = dataset
        self.device = torch.device(cfg.device)
        self.model = None

        self.base_lr = base_lr
        self.max_lr = max_lr
        self.weight_decay = weight_decay
        self.criterion = UltraEnhancedHurdleLoss(cfg.eps_smape, cfg.zero_weight, cfg.hurdle_lambda)
        self.ema = None
        self.epochs = epochs
        self.batch_size = batch_size

        if cfg.use_amp and torch.cuda.is_available():
            self.scaler = torch.cuda.amp.GradScaler()

        if torch.cuda.is_available():
            torch.backends.cuda.matmul.allow_tf32 = True
            torch.backends.cudnn.benchmark = True
            torch.backends.cudnn.deterministic = False
            torch.set_float32_matmul_precision('high')
            torch.cuda.empty_cache()
            print(f"🚀 GPU: {torch.cuda.get_device_name()}")
            print(f"🔥 VRAM: {torch.cuda.get_device_properties(0).total_memory / 1024**3:.1f}GB")

    def set_model(self, model):
        self.model = model
        self.ema = EMA(self.model, decay=self.cfg.ema_decay)

    def make_loaders_from_mask(self, mask_val: np.ndarray):
        idx_all = np.arange(len(self.dataset))
        val_idx = idx_all[mask_val]
        train_idx = idx_all[~mask_val]

        train_subset = torch.utils.data.Subset(self.dataset, train_idx)
        val_subset = torch.utils.data.Subset(self.dataset, val_idx)

        train_loader = DataLoader(
            train_subset, batch_size=self.batch_size, shuffle=True,
            num_workers=self.cfg.num_workers, pin_memory=self.cfg.pin_memory,
            persistent_workers=self.cfg.persistent_workers, drop_last=False
        )
        val_loader = DataLoader(
            val_subset, batch_size=self.batch_size, shuffle=False,
            num_workers=self.cfg.num_workers, pin_memory=self.cfg.pin_memory,
            persistent_workers=self.cfg.persistent_workers, drop_last=False
        )
        return train_loader, val_loader

    @torch.no_grad()
    def evaluate(self, loader: DataLoader, use_ema: bool = True) -> float:
        self.model.eval()
        backup = None
        if use_ema:
            backup = {k: v.detach().clone() for k, v in self.model.state_dict().items()}
            self.ema.apply_to(self.model)

        per_sample_losses = []
        per_sample_weights = []

        amp_ctx = torch.autocast(device_type='cuda', dtype=torch.bfloat16) if (
            self.cfg.use_amp and torch.cuda.is_available()
        ) else torch.cuda.amp.autocast(enabled=False)

        with amp_ctx:
            for batch in loader:
                x = batch["x"].to(self.device)
                y = batch["y"].to(self.device)
                past_cal = batch["past_cal"].to(self.device)
                fut_cal = batch["fut_cal"].to(self.device)
                store_idx = batch["store_idx"].to(self.device)
                cat_idx = batch["cat_idx"].to(self.device)
                type_idx = batch["type_idx"].to(self.device)
                sample_w = batch["sample_w"].to(self.device)
                pos_mask = batch["pos_mask"].to(self.device)

                v_pred, p_logits = self.model(x, past_cal, fut_cal, store_idx, cat_idx, type_idx)
                loss, sample_loss, sw = self.criterion(v_pred, p_logits, y, pos_mask, sample_w)
                per_sample_losses.append(sample_loss)
                per_sample_weights.append(sw)

        if use_ema and backup is not None:
            self.model.load_state_dict(backup)

        if len(per_sample_losses) == 0:
            return 0.0

        sample_loss_all = torch.cat(per_sample_losses)
        sw_all = torch.cat(per_sample_weights)
        val = (sample_loss_all * sw_all).sum().item() / float(sw_all.sum().item() + 1e-8)
        return val

    def train_with_loaders(self, train_loader: DataLoader, val_loader: DataLoader):
        self.optim = torch.optim.AdamW(
            self.model.parameters(),
            lr=self.base_lr,
            weight_decay=self.weight_decay,
            betas=(0.9, 0.999)
        )

        self.sched = torch.optim.lr_scheduler.OneCycleLR(
            self.optim,
            max_lr=self.max_lr,
            epochs=self.epochs,
            steps_per_epoch=len(train_loader),
            pct_start=0.05,
            div_factor=self.max_lr / self.base_lr
        )

        best_val = float("inf")
        best_state = None
        patience = 15
        no_improve = 0

        for epoch in range(1, self.epochs + 1):
            self.model.train()
            amp_ctx = torch.autocast(device_type='cuda', dtype=torch.bfloat16) if (
                self.cfg.use_amp and torch.cuda.is_available()
            ) else torch.cuda.amp.autocast(enabled=False)

            for batch in train_loader:
                x = batch["x"].to(self.device)
                y = batch["y"].to(self.device)
                past_cal = batch["past_cal"].to(self.device)
                fut_cal = batch["fut_cal"].to(self.device)
                store_idx = batch["store_idx"].to(self.device)
                cat_idx = batch["cat_idx"].to(self.device)
                type_idx = batch["type_idx"].to(self.device)
                sample_w = batch["sample_w"].to(self.device)
                pos_mask = batch["pos_mask"].to(self.device)

                with amp_ctx:
                    v_pred, p_logits = self.model(x, past_cal, fut_cal, store_idx, cat_idx, type_idx)
                    loss, _, _ = self.criterion(v_pred, p_logits, y, pos_mask, sample_w)

                self.optim.zero_grad(set_to_none=True)
                if self.cfg.use_amp and torch.cuda.is_available():
                    self.scaler.scale(loss).backward()
                    self.scaler.unscale_(self.optim)
                    torch.nn.utils.clip_grad_norm_(self.model.parameters(), 0.5)
                    self.scaler.step(self.optim)
                    self.scaler.update()
                else:
                    loss.backward()
                    torch.nn.utils.clip_grad_norm_(self.model.parameters(), 0.5)
                    self.optim.step()
                self.sched.step()
                self.ema.update(self.model)

            val_loss = self.evaluate(val_loader, use_ema=True)
            print(f"[Epoch {epoch:03d}] val_loss: {val_loss:.5f}")

            if val_loss < best_val:
                best_val = val_loss
                best_state = {k: v.detach().cpu().clone() for k, v in self.model.state_dict().items()}
                no_improve = 0
            else:
                no_improve += 1
                if no_improve >= patience:
                    print(f"Early stopping at epoch {epoch}")
                    break

        if best_state is not None:
            self.model.load_state_dict(best_state)

        return self.model, best_val

# =====================
# Validation Masking Util # 오류 생겨서 추가했던 코드임
# =====================
def make_val_mask_by_week(dataset, end_date: str) -> np.ndarray:
    """
    특정 날짜까지의 데이터만 학습에 사용하고, 이후 데이터는 검증에 사용하기 위한 마스크를 생성합니다.

    Args:
        dataset: EnhancedNHiTSDataset 객체.
        end_date: 검증 시작 전 마지막 날짜 (예: '2024-06-14').

    Returns:
        numpy.ndarray: True/False로 구성된 마스크 배열.
    """
    cutoff = pd.to_datetime(end_date)
    return dataset.target_end_dates > cutoff

# ==============================================================================
# 5. Prediction Utils (TCN과 동일하게 사용)
# ==============================================================================
@torch.no_grad()
def predict_one_file(cfg: EnhancedNHiTSConfig, model: EnhancedTCNModel, test_df: pd.DataFrame,
                     store2idx: Dict, cat2idx: Dict, type2idx: Dict) -> pd.DataFrame:
    device = torch.device(cfg.device)
    tdf = test_df.copy()
    tdf[cfg.date_col] = pd.to_datetime(tdf[cfg.date_col])
    tdf[cfg.target_col] = tdf[cfg.target_col].clip(lower=0)

    last_date = tdf[cfg.date_col].max()
    future_dates = [last_date + pd.Timedelta(days=i) for i in range(1, cfg.out_len + 1)]

    df_with_future = tdf.copy()
    future_df = pd.DataFrame({
        cfg.date_col: future_dates,
        cfg.target_col: [0.0] * cfg.out_len
    })

    all_items = tdf[cfg.item_col].unique()
    future_df_full = pd.concat([
        future_df.assign(**{cfg.item_col: item}) for item in all_items
    ], ignore_index=True)

    df_with_future = pd.concat([df_with_future, future_df_full], ignore_index=True)
    df_with_future.sort_values(by=[cfg.item_col, cfg.date_col], inplace=True)

    holidays_set = set(pd.to_datetime(cfg.custom_holidays_list))
    df_all_feats = build_enhanced_features(df_with_future, holidays_set)

    past_cal_list = []
    fut_cal_list = []
    x_list = []

    for item in all_items:
        item_df = df_all_feats[df_all_feats[cfg.item_col] == item].copy()

        item_sales = item_df[cfg.target_col].values
        x_list.append(item_sales[-(cfg.in_len+cfg.out_len) : -cfg.out_len])

        cal_feat_cols = df_all_feats.columns.drop([cfg.date_col, cfg.item_col, cfg.target_col])
        item_cal_feats = item_df[cal_feat_cols].values

        past_cal_list.append(item_cal_feats[-(cfg.in_len+cfg.out_len) : -cfg.out_len, :])

        fut_cal_list.append(item_cal_feats[-cfg.out_len:, :])

    x = np.stack(x_list, axis=0).astype(np.float32)
    past_cal = np.stack(past_cal_list, axis=0).astype(np.float32)
    fut_cal = np.stack(fut_cal_list, axis=0).astype(np.float32)

    if cfg.log1p:
        x = np.log1p(x)

    x = torch.from_numpy(x).float().to(device)
    past_cal_b = torch.from_numpy(past_cal).float().to(device)
    fut_cal_b = torch.from_numpy(fut_cal).float().to(device)

    stores = [parse_store_name(it) for it in all_items]
    menus = [parse_menu_name(it) for it in all_items]

    store_idx = torch.tensor([store2idx.get(s, 0) for s in stores], dtype=torch.long, device=device)
    cat_idx = torch.tensor([cat2idx.get(get_menu_category(m), 0) for m in menus], dtype=torch.long, device=device)
    type_idx = torch.tensor([type2idx.get(get_store_type(s), 0) for s in stores], dtype=torch.long, device=device)

    amp_ctx = torch.autocast(device_type='cuda', dtype=torch.bfloat16) if (
        cfg.use_amp and torch.cuda.is_available()
    ) else torch.cuda.amp.autocast(enabled=False)

    model.eval()
    with amp_ctx:
        v_pred, p_logits = model(x, past_cal_b, fut_cal_b, store_idx, cat_idx, type_idx)
        y_val = torch.expm1(v_pred).clamp_min(0.0)
        y_prob = torch.sigmoid(p_logits)
        y_hat = (y_prob * y_val).clamp_min(0.0).cpu().numpy()

    return pd.DataFrame(y_hat.T, columns=all_items)

# ==============================================================================
# 6. 메인 실행 블록 (수정: 재학습 후 예측)
# ==============================================================================
if __name__ == "__main__":
    cfg = EnhancedNHiTSConfig()
    if cfg.store_weights is None:
        cfg.store_weights = DEFAULT_STORE_WEIGHTS
    if cfg.custom_holidays_list is None:
        cfg.custom_holidays_list = DEFAULT_CUSTOM_HOLIDAYS

    set_seed(cfg.seed)

    FAST_MODE = True
    if FAST_MODE:
        cfg.USE_OPTUNA = False
        cfg.EPOCHS_FULL = 60
        cfg.BATCH_FULL = 1024

    if FAST_MODE:
        print("⚡️ optuna를 하지 않고 지정된 피팅값으로 실행.")
    else:
        print("퇴근 가즈아ㅏㅏㅏ🔥")

    if cfg.USE_OPTUNA:
        print("🔧 Optuna N-HiTS 하이퍼파라미터 튜닝...")
        print(f"✅ 최적 N-HiTS 설정 완료!")

    print("📚 Enhanced TCN 모델 학습...")
    train_df = pd.read_csv(cfg.train_csv)

    if '영업장명_메뉴명' not in train_df.columns:
        train_df['영업장명_메뉴명'] = train_df['영업장명'] + '_' + train_df['메뉴명']

    ds = EnhancedNHiTSDataset(cfg, train_df)

    cal_dim = ds.cal_feats.shape[1]
    model = EnhancedTCNModel(
        cfg.in_len, cfg.out_len, cal_dim, ds.n_stores,
        ds.n_categories, ds.n_types, cfg
    ).to(cfg.device)

    trainer = EnhancedNHiTSTrainer(cfg, ds, cfg.EPOCHS_FULL, cfg.BATCH_FULL,
                                   cfg.BASE_LR_FULL, cfg.MAX_LR_FULL, cfg.WD_FULL)

    trainer.set_model(model)

    mask_val = make_val_mask_by_week(ds, cfg.cv_fold_end_dates[0])
    train_loader, val_loader = trainer.make_loaders_from_mask(mask_val)
    model, final_val_loss = trainer.train_with_loaders(train_loader, val_loader)

    print(f"🎊 최종 검증 손실: {final_val_loss:.5f}")
    print(f"📈 예상 개선: {final_val_loss:.3f}")

    os.makedirs(os.path.dirname(cfg.out_submission_csv), exist_ok=True)
    model_save_path = "./enhanced_tcn_model.pth" # 여기 경로도 바꾸세여
    torch.save({
        "model_state": model.state_dict(),
        "cfg": cfg.__dict__,
        "store2idx": ds.store2idx,
        "cat2idx": ds.cat2idx,
        "type2idx": ds.type2idx,
        "final_val_loss": final_val_loss,
    }, model_save_path)
    print(f"[저장] {model_save_path}")

  # 여기 코드로 했을 때 submission 파일이 영업일자명이 제대로 안나왔어서 밑에서 모델 다시 불러왔어요,,
  # 일단 혹시 몰라서 주석 처리만 해놨습니다!
  #  print("🔮 Enhanced TCN 예측...")
  #  test_files = sorted(glob.glob(cfg.test_glob))
  #  sub_template = pd.read_csv(cfg.submission_template_csv)
  #  all_preds_df = pd.DataFrame(columns=sub_template.columns)

  #  for test_idx, test_file in enumerate(test_files):
  #     print(f" 📊 {test_file} 처리 중...")
 #      tdf = pd.read_csv(test_file)
  #     if '영업장명_메뉴명' not in tdf.columns:
  #          tdf['영업장명_메뉴명'] = tdf['영업장명'] + '_' + tdf['메뉴명']

  #     submit_block = predict_one_file(cfg, model, tdf, ds.store2idx, ds.cat2idx, ds.type2idx)
  #     submit_block.index = [f"TEST_{test_idx:02d}+{k}일" for k in range(1, cfg.out_len+1)]
  #     all_preds_df = pd.concat([all_preds_df, submit_block], ignore_index=True)

   # final_submit = all_preds_df.reindex(columns=sub_template.columns, fill_value=0)

  # num_cols = final_submit.columns.drop('영업일자')
 #  for col in num_cols:
 #       Q95 = final_submit[col].quantile(0.95)
#      final_submit[col] = np.where(
#           final_submit[col] > Q95 * 2.0,
#           Q95 * 1.5,
#           final_submit[col]
#       )

#    final_submit[num_cols] = np.rint(np.clip(final_submit[num_cols].values, a_min=0, a_max=None)).astype(int)
#    final_submit.to_csv(cfg.out_submission_csv, index=False, encoding="utf-8-sig")

#   print(f"✅ Enhanced TCN 완료! → {cfg.out_submission_csv}")
#   print("🏆 TCN + Enhanced Features 학습 완료")

# 5. 메인 실행 블록 (수정: 저장된 모델 불러와 예측)
# ==============================================================================
if __name__ == "__main__":
    cfg = EnhancedNHiTSConfig()
    if cfg.store_weights is None:
        cfg.store_weights = DEFAULT_STORE_WEIGHTS
    if cfg.custom_holidays_list is None:
        cfg.custom_holidays_list = DEFAULT_CUSTOM_HOLIDAYS

    set_seed(cfg.seed)

    print("💾 저장된 모델 불러오는 중...")
    model_path = "./enhanced_tcn_model.pth"
    checkpoint = torch.load(model_path, map_location=cfg.device)

    train_df = pd.read_csv(cfg.train_csv)
    if '영업장명_메뉴명' not in train_df.columns:
        train_df['영업장명_메뉴명'] = train_df['영업장명'] + '_' + train_df['메뉴명']
    ds_meta = EnhancedNHiTSDataset(cfg, train_df)

    cal_dim = ds_meta.cal_feats.shape[1]
    model = EnhancedTCNModel(
        cfg.in_len, cfg.out_len, cal_dim, ds_meta.n_stores,
        ds_meta.n_categories, ds_meta.n_types, cfg
    ).to(cfg.device)

    model.load_state_dict(checkpoint['model_state'])
    print("✅ 모델 로드 완료!")

    print("🔮 Enhanced TCN 예측...")
    test_files = sorted(glob.glob(cfg.test_glob))
    sub_template = pd.read_csv(cfg.submission_template_csv)
    all_preds_df = pd.DataFrame()

    for test_idx, test_file in enumerate(test_files):
        print(f" 📊 {test_file} 처리 중...")
        tdf = pd.read_csv(test_file)
        if '영업장명_메뉴명' not in tdf.columns:
            tdf['영업장명_메뉴명'] = tdf['영업장명'] + '_' + tdf['메뉴명']

        submit_block = predict_one_file(cfg, model, tdf, ds_meta.store2idx, ds_meta.cat2idx, ds_meta.type2idx)
        submit_block.index = [f"TEST_{test_idx:02d}+{k}일" for k in range(1, cfg.out_len+1)]
        all_preds_df = pd.concat([all_preds_df, submit_block], ignore_index=False)

    final_submit = all_preds_df.reset_index(inplace=False).rename(columns={'index': '영업일자'})
    final_submit = final_submit.reindex(columns=sub_template.columns, fill_value=0)

    num_cols = final_submit.columns.drop('영업일자')
    for col in num_cols:
        Q95 = final_submit[col].quantile(0.95)
        final_submit[col] = np.where(
            final_submit[col] > Q95 * 2.0,
            Q95 * 1.5,
            final_submit[col]
        )

    final_submit[num_cols] = np.rint(np.clip(final_submit[num_cols].values, a_min=0, a_max=None)).astype(int)
    final_submit.to_csv(cfg.out_submission_csv, index=False, encoding="utf-8-sig")

    print(f"✅ Enhanced TCN 완료! → {cfg.out_submission_csv}")
    print("🏆 TCN + Enhanced Features 학습 완료")
